// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1406327045;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__timeline__compute_stats_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "compute_stats",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::timeline::PipelineRequest>::sse_decode(&mut deserializer);
            let api_cell_size_deg = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::timeline::compute_stats(
                        api_request,
                        api_cell_size_deg,
                    ))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__timeline__filters_input_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "filters_input_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::timeline::FiltersInput::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__timeline__pipeline_request_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pipeline_request_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::timeline::PipelineRequest::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__timeline__pipeline_response_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pipeline_response_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::timeline::PipelineResponse::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__timeline__plan_video_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "plan_video",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::timeline::PipelineRequest>::sse_decode(&mut deserializer);
            let api_params = <crate::api::timeline::VideoParams>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::timeline::plan_video(
                        api_request,
                        api_params,
                    ))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__timeline__run_pipeline_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "run_pipeline",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::timeline::PipelineRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::timeline::run_pipeline(api_request))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__timeline__stats_output_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stats_output_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::timeline::StatsOutput::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__timeline__video_plan_result_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "video_plan_result_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::timeline::VideoPlanResult::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::timeline::BucketOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_key = <String>::sse_decode(deserializer);
        let mut var_placeId = <Option<i64>>::sse_decode(deserializer);
        let mut var_count = <u32>::sse_decode(deserializer);
        let mut var_durationMs = <i64>::sse_decode(deserializer);
        let mut var_distanceM = <f64>::sse_decode(deserializer);
        return crate::api::timeline::BucketOutput {
            key: var_key,
            place_id: var_placeId,
            count: var_count,
            duration_ms: var_durationMs,
            distance_m: var_distanceM,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::timeline::FiltersInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_periodStartUtc = <Option<i64>>::sse_decode(deserializer);
        let mut var_periodEndUtc = <Option<i64>>::sse_decode(deserializer);
        let mut var_userPlaceId = <Option<i64>>::sse_decode(deserializer);
        let mut var_geoPlaceId = <Option<i64>>::sse_decode(deserializer);
        let mut var_modes = <Vec<crate::api::timeline::TravelMode>>::sse_decode(deserializer);
        return crate::api::timeline::FiltersInput {
            period_start_utc: var_periodStartUtc,
            period_end_utc: var_periodEndUtc,
            user_place_id: var_userPlaceId,
            geo_place_id: var_geoPlaceId,
            modes: var_modes,
        };
    }
}

impl SseDecode for crate::api::timeline::FrameOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_index = <u32>::sse_decode(deserializer);
        let mut var_timestampUtc = <i64>::sse_decode(deserializer);
        let mut var_revealedPoints = <u32>::sse_decode(deserializer);
        let mut var_revealedSegments = <u32>::sse_decode(deserializer);
        return crate::api::timeline::FrameOutput {
            index: var_index,
            timestamp_utc: var_timestampUtc,
            revealed_points: var_revealedPoints,
            revealed_segments: var_revealedSegments,
        };
    }
}

impl SseDecode for crate::api::timeline::HeatCellOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_lat = <f64>::sse_decode(deserializer);
        let mut var_lon = <f64>::sse_decode(deserializer);
        let mut var_count = <u32>::sse_decode(deserializer);
        return crate::api::timeline::HeatCellOutput {
            lat: var_lat,
            lon: var_lon,
            count: var_count,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::timeline::BucketOutput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::timeline::BucketOutput>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::timeline::FrameOutput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::timeline::FrameOutput>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::timeline::HeatCellOutput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::timeline::HeatCellOutput>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::timeline::OverrideInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::timeline::OverrideInput>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::timeline::PointInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::timeline::PointInput>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<f64>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<i64>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::timeline::PrivateZoneInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::timeline::PrivateZoneInput>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::timeline::ResolvedPointOutput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::timeline::ResolvedPointOutput>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::timeline::ResolvedSegmentOutput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::timeline::ResolvedSegmentOutput>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::timeline::ResolvedVisitOutput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::timeline::ResolvedVisitOutput>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::timeline::SegmentInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::timeline::SegmentInput>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::timeline::TravelMode> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::timeline::TravelMode>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::timeline::UserPlaceInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::timeline::UserPlaceInput>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::timeline::VisitInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::timeline::VisitInput>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::timeline::VideoPlanErrorKind> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::timeline::VideoPlanErrorKind>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::timeline::OverrideInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_localDate = <i32>::sse_decode(deserializer);
        let mut var_startLatR = <f64>::sse_decode(deserializer);
        let mut var_startLonR = <f64>::sse_decode(deserializer);
        let mut var_endLatR = <f64>::sse_decode(deserializer);
        let mut var_endLonR = <f64>::sse_decode(deserializer);
        let mut var_correctedMode = <crate::api::timeline::TravelMode>::sse_decode(deserializer);
        let mut var_sourceStartTsUtc = <i64>::sse_decode(deserializer);
        return crate::api::timeline::OverrideInput {
            id: var_id,
            local_date: var_localDate,
            start_lat_r: var_startLatR,
            start_lon_r: var_startLonR,
            end_lat_r: var_endLatR,
            end_lon_r: var_endLonR,
            corrected_mode: var_correctedMode,
            source_start_ts_utc: var_sourceStartTsUtc,
        };
    }
}

impl SseDecode for crate::api::timeline::PipelineRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_points = <Vec<crate::api::timeline::PointInput>>::sse_decode(deserializer);
        let mut var_visits = <Vec<crate::api::timeline::VisitInput>>::sse_decode(deserializer);
        let mut var_segments = <Vec<crate::api::timeline::SegmentInput>>::sse_decode(deserializer);
        let mut var_userPlaces =
            <Vec<crate::api::timeline::UserPlaceInput>>::sse_decode(deserializer);
        let mut var_privateZones =
            <Vec<crate::api::timeline::PrivateZoneInput>>::sse_decode(deserializer);
        let mut var_overrides =
            <Vec<crate::api::timeline::OverrideInput>>::sse_decode(deserializer);
        let mut var_filters = <crate::api::timeline::FiltersInput>::sse_decode(deserializer);
        return crate::api::timeline::PipelineRequest {
            points: var_points,
            visits: var_visits,
            segments: var_segments,
            user_places: var_userPlaces,
            private_zones: var_privateZones,
            overrides: var_overrides,
            filters: var_filters,
        };
    }
}

impl SseDecode for crate::api::timeline::PipelineResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_points =
            <Vec<crate::api::timeline::ResolvedPointOutput>>::sse_decode(deserializer);
        let mut var_visits =
            <Vec<crate::api::timeline::ResolvedVisitOutput>>::sse_decode(deserializer);
        let mut var_segments =
            <Vec<crate::api::timeline::ResolvedSegmentOutput>>::sse_decode(deserializer);
        let mut var_orphanOverrideIds = <Vec<i64>>::sse_decode(deserializer);
        return crate::api::timeline::PipelineResponse {
            points: var_points,
            visits: var_visits,
            segments: var_segments,
            orphan_override_ids: var_orphanOverrideIds,
        };
    }
}

impl SseDecode for crate::api::timeline::PlaceOrigin {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::timeline::PlaceOrigin::UserPlace,
            1 => crate::api::timeline::PlaceOrigin::GeoPlace,
            2 => crate::api::timeline::PlaceOrigin::Coordinates,
            _ => unreachable!("Invalid variant for PlaceOrigin: {}", inner),
        };
    }
}

impl SseDecode for crate::api::timeline::PointInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_timestampUtc = <i64>::sse_decode(deserializer);
        let mut var_tzOffsetMinutes = <i32>::sse_decode(deserializer);
        let mut var_lat = <f64>::sse_decode(deserializer);
        let mut var_lon = <f64>::sse_decode(deserializer);
        return crate::api::timeline::PointInput {
            timestamp_utc: var_timestampUtc,
            tz_offset_minutes: var_tzOffsetMinutes,
            lat: var_lat,
            lon: var_lon,
        };
    }
}

impl SseDecode for crate::api::timeline::PrivateZoneInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_lat = <Option<f64>>::sse_decode(deserializer);
        let mut var_lon = <Option<f64>>::sse_decode(deserializer);
        let mut var_radiusM = <Option<f64>>::sse_decode(deserializer);
        let mut var_polygon = <Vec<f64>>::sse_decode(deserializer);
        return crate::api::timeline::PrivateZoneInput {
            id: var_id,
            label: var_label,
            lat: var_lat,
            lon: var_lon,
            radius_m: var_radiusM,
            polygon: var_polygon,
        };
    }
}

impl SseDecode for crate::api::timeline::ResolvedPointOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_timestampUtc = <i64>::sse_decode(deserializer);
        let mut var_lat = <f64>::sse_decode(deserializer);
        let mut var_lon = <f64>::sse_decode(deserializer);
        return crate::api::timeline::ResolvedPointOutput {
            timestamp_utc: var_timestampUtc,
            lat: var_lat,
            lon: var_lon,
        };
    }
}

impl SseDecode for crate::api::timeline::ResolvedSegmentOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_startTsUtc = <i64>::sse_decode(deserializer);
        let mut var_startTzOffsetMinutes = <i32>::sse_decode(deserializer);
        let mut var_endTsUtc = <i64>::sse_decode(deserializer);
        let mut var_endTzOffsetMinutes = <i32>::sse_decode(deserializer);
        let mut var_startLat = <f64>::sse_decode(deserializer);
        let mut var_startLon = <f64>::sse_decode(deserializer);
        let mut var_endLat = <f64>::sse_decode(deserializer);
        let mut var_endLon = <f64>::sse_decode(deserializer);
        let mut var_distanceM = <Option<f64>>::sse_decode(deserializer);
        let mut var_mode = <crate::api::timeline::TravelMode>::sse_decode(deserializer);
        let mut var_corrected = <bool>::sse_decode(deserializer);
        let mut var_startPlaceLabel = <Option<String>>::sse_decode(deserializer);
        let mut var_endPlaceLabel = <Option<String>>::sse_decode(deserializer);
        return crate::api::timeline::ResolvedSegmentOutput {
            id: var_id,
            start_ts_utc: var_startTsUtc,
            start_tz_offset_minutes: var_startTzOffsetMinutes,
            end_ts_utc: var_endTsUtc,
            end_tz_offset_minutes: var_endTzOffsetMinutes,
            start_lat: var_startLat,
            start_lon: var_startLon,
            end_lat: var_endLat,
            end_lon: var_endLon,
            distance_m: var_distanceM,
            mode: var_mode,
            corrected: var_corrected,
            start_place_label: var_startPlaceLabel,
            end_place_label: var_endPlaceLabel,
        };
    }
}

impl SseDecode for crate::api::timeline::ResolvedVisitOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_arrivalTsUtc = <i64>::sse_decode(deserializer);
        let mut var_arrivalTzOffsetMinutes = <i32>::sse_decode(deserializer);
        let mut var_departureTsUtc = <i64>::sse_decode(deserializer);
        let mut var_departureTzOffsetMinutes = <i32>::sse_decode(deserializer);
        let mut var_lat = <f64>::sse_decode(deserializer);
        let mut var_lon = <f64>::sse_decode(deserializer);
        let mut var_placeLabel = <Option<String>>::sse_decode(deserializer);
        let mut var_placeOrigin = <crate::api::timeline::PlaceOrigin>::sse_decode(deserializer);
        let mut var_placeId = <Option<i64>>::sse_decode(deserializer);
        return crate::api::timeline::ResolvedVisitOutput {
            id: var_id,
            arrival_ts_utc: var_arrivalTsUtc,
            arrival_tz_offset_minutes: var_arrivalTzOffsetMinutes,
            departure_ts_utc: var_departureTsUtc,
            departure_tz_offset_minutes: var_departureTzOffsetMinutes,
            lat: var_lat,
            lon: var_lon,
            place_label: var_placeLabel,
            place_origin: var_placeOrigin,
            place_id: var_placeId,
        };
    }
}

impl SseDecode for crate::api::timeline::SegmentInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_startTsUtc = <i64>::sse_decode(deserializer);
        let mut var_startTzOffsetMinutes = <i32>::sse_decode(deserializer);
        let mut var_endTsUtc = <i64>::sse_decode(deserializer);
        let mut var_endTzOffsetMinutes = <i32>::sse_decode(deserializer);
        let mut var_startLat = <f64>::sse_decode(deserializer);
        let mut var_startLon = <f64>::sse_decode(deserializer);
        let mut var_endLat = <f64>::sse_decode(deserializer);
        let mut var_endLon = <f64>::sse_decode(deserializer);
        let mut var_distanceM = <Option<f64>>::sse_decode(deserializer);
        let mut var_detectedMode = <crate::api::timeline::TravelMode>::sse_decode(deserializer);
        return crate::api::timeline::SegmentInput {
            id: var_id,
            start_ts_utc: var_startTsUtc,
            start_tz_offset_minutes: var_startTzOffsetMinutes,
            end_ts_utc: var_endTsUtc,
            end_tz_offset_minutes: var_endTzOffsetMinutes,
            start_lat: var_startLat,
            start_lon: var_startLon,
            end_lat: var_endLat,
            end_lon: var_endLon,
            distance_m: var_distanceM,
            detected_mode: var_detectedMode,
        };
    }
}

impl SseDecode for crate::api::timeline::StatsOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_density = <Vec<crate::api::timeline::HeatCellOutput>>::sse_decode(deserializer);
        let mut var_places = <Vec<crate::api::timeline::BucketOutput>>::sse_decode(deserializer);
        let mut var_modes = <Vec<crate::api::timeline::BucketOutput>>::sse_decode(deserializer);
        let mut var_hours = <Vec<crate::api::timeline::BucketOutput>>::sse_decode(deserializer);
        let mut var_weekdays = <Vec<crate::api::timeline::BucketOutput>>::sse_decode(deserializer);
        let mut var_totalDistanceM = <f64>::sse_decode(deserializer);
        let mut var_visitCount = <u32>::sse_decode(deserializer);
        let mut var_segmentCount = <u32>::sse_decode(deserializer);
        return crate::api::timeline::StatsOutput {
            density: var_density,
            places: var_places,
            modes: var_modes,
            hours: var_hours,
            weekdays: var_weekdays,
            total_distance_m: var_totalDistanceM,
            visit_count: var_visitCount,
            segment_count: var_segmentCount,
        };
    }
}

impl SseDecode for crate::api::timeline::TravelMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::timeline::TravelMode::Walking,
            1 => crate::api::timeline::TravelMode::Running,
            2 => crate::api::timeline::TravelMode::Cycling,
            3 => crate::api::timeline::TravelMode::InVehicle,
            4 => crate::api::timeline::TravelMode::InBus,
            5 => crate::api::timeline::TravelMode::InTrain,
            6 => crate::api::timeline::TravelMode::Boat,
            7 => crate::api::timeline::TravelMode::Motorcycling,
            8 => crate::api::timeline::TravelMode::Flight,
            9 => crate::api::timeline::TravelMode::Unknown,
            _ => unreachable!("Invalid variant for TravelMode: {}", inner),
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::timeline::UserPlaceInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_lat = <f64>::sse_decode(deserializer);
        let mut var_lon = <f64>::sse_decode(deserializer);
        let mut var_radiusM = <f64>::sse_decode(deserializer);
        return crate::api::timeline::UserPlaceInput {
            id: var_id,
            label: var_label,
            lat: var_lat,
            lon: var_lon,
            radius_m: var_radiusM,
        };
    }
}

impl SseDecode for crate::api::timeline::VideoParams {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_durationS = <u32>::sse_decode(deserializer);
        let mut var_periodStartUtc = <i64>::sse_decode(deserializer);
        let mut var_periodEndUtc = <i64>::sse_decode(deserializer);
        let mut var_style = <crate::api::timeline::VideoStyle>::sse_decode(deserializer);
        let mut var_title = <String>::sse_decode(deserializer);
        return crate::api::timeline::VideoParams {
            duration_s: var_durationS,
            period_start_utc: var_periodStartUtc,
            period_end_utc: var_periodEndUtc,
            style: var_style,
            title: var_title,
        };
    }
}

impl SseDecode for crate::api::timeline::VideoPlanErrorKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::timeline::VideoPlanErrorKind::UnsupportedDuration,
            1 => crate::api::timeline::VideoPlanErrorKind::EmptyPeriod,
            2 => crate::api::timeline::VideoPlanErrorKind::NothingToRender,
            _ => unreachable!("Invalid variant for VideoPlanErrorKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::timeline::VideoPlanResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_error =
            <Option<crate::api::timeline::VideoPlanErrorKind>>::sse_decode(deserializer);
        let mut var_frames = <Vec<crate::api::timeline::FrameOutput>>::sse_decode(deserializer);
        let mut var_fps = <u32>::sse_decode(deserializer);
        return crate::api::timeline::VideoPlanResult {
            error: var_error,
            frames: var_frames,
            fps: var_fps,
        };
    }
}

impl SseDecode for crate::api::timeline::VideoStyle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::timeline::VideoStyle::Classic,
            1 => crate::api::timeline::VideoStyle::Night,
            2 => crate::api::timeline::VideoStyle::Minimal,
            _ => unreachable!("Invalid variant for VideoStyle: {}", inner),
        };
    }
}

impl SseDecode for crate::api::timeline::VisitInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_arrivalTsUtc = <i64>::sse_decode(deserializer);
        let mut var_arrivalTzOffsetMinutes = <i32>::sse_decode(deserializer);
        let mut var_departureTsUtc = <i64>::sse_decode(deserializer);
        let mut var_departureTzOffsetMinutes = <i32>::sse_decode(deserializer);
        let mut var_lat = <f64>::sse_decode(deserializer);
        let mut var_lon = <f64>::sse_decode(deserializer);
        return crate::api::timeline::VisitInput {
            id: var_id,
            arrival_ts_utc: var_arrivalTsUtc,
            arrival_tz_offset_minutes: var_arrivalTzOffsetMinutes,
            departure_ts_utc: var_departureTsUtc,
            departure_tz_offset_minutes: var_departureTzOffsetMinutes,
            lat: var_lat,
            lon: var_lon,
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__timeline__compute_stats_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__timeline__filters_input_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        3 => wire__crate__api__timeline__pipeline_request_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        4 => wire__crate__api__timeline__pipeline_response_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        5 => wire__crate__api__timeline__plan_video_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__timeline__run_pipeline_impl(port, ptr, rust_vec_len, data_len),
        7 => {
            wire__crate__api__timeline__stats_output_default_impl(port, ptr, rust_vec_len, data_len)
        }
        8 => wire__crate__api__timeline__video_plan_result_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::BucketOutput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.key.into_into_dart().into_dart(),
            self.place_id.into_into_dart().into_dart(),
            self.count.into_into_dart().into_dart(),
            self.duration_ms.into_into_dart().into_dart(),
            self.distance_m.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::BucketOutput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::BucketOutput>
    for crate::api::timeline::BucketOutput
{
    fn into_into_dart(self) -> crate::api::timeline::BucketOutput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::FiltersInput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.period_start_utc.into_into_dart().into_dart(),
            self.period_end_utc.into_into_dart().into_dart(),
            self.user_place_id.into_into_dart().into_dart(),
            self.geo_place_id.into_into_dart().into_dart(),
            self.modes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::FiltersInput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::FiltersInput>
    for crate::api::timeline::FiltersInput
{
    fn into_into_dart(self) -> crate::api::timeline::FiltersInput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::FrameOutput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.index.into_into_dart().into_dart(),
            self.timestamp_utc.into_into_dart().into_dart(),
            self.revealed_points.into_into_dart().into_dart(),
            self.revealed_segments.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::FrameOutput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::FrameOutput>
    for crate::api::timeline::FrameOutput
{
    fn into_into_dart(self) -> crate::api::timeline::FrameOutput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::HeatCellOutput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.lat.into_into_dart().into_dart(),
            self.lon.into_into_dart().into_dart(),
            self.count.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::HeatCellOutput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::HeatCellOutput>
    for crate::api::timeline::HeatCellOutput
{
    fn into_into_dart(self) -> crate::api::timeline::HeatCellOutput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::OverrideInput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.local_date.into_into_dart().into_dart(),
            self.start_lat_r.into_into_dart().into_dart(),
            self.start_lon_r.into_into_dart().into_dart(),
            self.end_lat_r.into_into_dart().into_dart(),
            self.end_lon_r.into_into_dart().into_dart(),
            self.corrected_mode.into_into_dart().into_dart(),
            self.source_start_ts_utc.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::OverrideInput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::OverrideInput>
    for crate::api::timeline::OverrideInput
{
    fn into_into_dart(self) -> crate::api::timeline::OverrideInput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::PipelineRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.points.into_into_dart().into_dart(),
            self.visits.into_into_dart().into_dart(),
            self.segments.into_into_dart().into_dart(),
            self.user_places.into_into_dart().into_dart(),
            self.private_zones.into_into_dart().into_dart(),
            self.overrides.into_into_dart().into_dart(),
            self.filters.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::PipelineRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::PipelineRequest>
    for crate::api::timeline::PipelineRequest
{
    fn into_into_dart(self) -> crate::api::timeline::PipelineRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::PipelineResponse {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.points.into_into_dart().into_dart(),
            self.visits.into_into_dart().into_dart(),
            self.segments.into_into_dart().into_dart(),
            self.orphan_override_ids.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::PipelineResponse
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::PipelineResponse>
    for crate::api::timeline::PipelineResponse
{
    fn into_into_dart(self) -> crate::api::timeline::PipelineResponse {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::PlaceOrigin {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::UserPlace => 0.into_dart(),
            Self::GeoPlace => 1.into_dart(),
            Self::Coordinates => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::PlaceOrigin
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::PlaceOrigin>
    for crate::api::timeline::PlaceOrigin
{
    fn into_into_dart(self) -> crate::api::timeline::PlaceOrigin {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::PointInput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.timestamp_utc.into_into_dart().into_dart(),
            self.tz_offset_minutes.into_into_dart().into_dart(),
            self.lat.into_into_dart().into_dart(),
            self.lon.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::PointInput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::PointInput>
    for crate::api::timeline::PointInput
{
    fn into_into_dart(self) -> crate::api::timeline::PointInput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::PrivateZoneInput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.lat.into_into_dart().into_dart(),
            self.lon.into_into_dart().into_dart(),
            self.radius_m.into_into_dart().into_dart(),
            self.polygon.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::PrivateZoneInput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::PrivateZoneInput>
    for crate::api::timeline::PrivateZoneInput
{
    fn into_into_dart(self) -> crate::api::timeline::PrivateZoneInput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::ResolvedPointOutput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.timestamp_utc.into_into_dart().into_dart(),
            self.lat.into_into_dart().into_dart(),
            self.lon.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::ResolvedPointOutput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::ResolvedPointOutput>
    for crate::api::timeline::ResolvedPointOutput
{
    fn into_into_dart(self) -> crate::api::timeline::ResolvedPointOutput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::ResolvedSegmentOutput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.start_ts_utc.into_into_dart().into_dart(),
            self.start_tz_offset_minutes.into_into_dart().into_dart(),
            self.end_ts_utc.into_into_dart().into_dart(),
            self.end_tz_offset_minutes.into_into_dart().into_dart(),
            self.start_lat.into_into_dart().into_dart(),
            self.start_lon.into_into_dart().into_dart(),
            self.end_lat.into_into_dart().into_dart(),
            self.end_lon.into_into_dart().into_dart(),
            self.distance_m.into_into_dart().into_dart(),
            self.mode.into_into_dart().into_dart(),
            self.corrected.into_into_dart().into_dart(),
            self.start_place_label.into_into_dart().into_dart(),
            self.end_place_label.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::ResolvedSegmentOutput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::ResolvedSegmentOutput>
    for crate::api::timeline::ResolvedSegmentOutput
{
    fn into_into_dart(self) -> crate::api::timeline::ResolvedSegmentOutput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::ResolvedVisitOutput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.arrival_ts_utc.into_into_dart().into_dart(),
            self.arrival_tz_offset_minutes.into_into_dart().into_dart(),
            self.departure_ts_utc.into_into_dart().into_dart(),
            self.departure_tz_offset_minutes
                .into_into_dart()
                .into_dart(),
            self.lat.into_into_dart().into_dart(),
            self.lon.into_into_dart().into_dart(),
            self.place_label.into_into_dart().into_dart(),
            self.place_origin.into_into_dart().into_dart(),
            self.place_id.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::ResolvedVisitOutput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::ResolvedVisitOutput>
    for crate::api::timeline::ResolvedVisitOutput
{
    fn into_into_dart(self) -> crate::api::timeline::ResolvedVisitOutput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::SegmentInput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.start_ts_utc.into_into_dart().into_dart(),
            self.start_tz_offset_minutes.into_into_dart().into_dart(),
            self.end_ts_utc.into_into_dart().into_dart(),
            self.end_tz_offset_minutes.into_into_dart().into_dart(),
            self.start_lat.into_into_dart().into_dart(),
            self.start_lon.into_into_dart().into_dart(),
            self.end_lat.into_into_dart().into_dart(),
            self.end_lon.into_into_dart().into_dart(),
            self.distance_m.into_into_dart().into_dart(),
            self.detected_mode.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::SegmentInput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::SegmentInput>
    for crate::api::timeline::SegmentInput
{
    fn into_into_dart(self) -> crate::api::timeline::SegmentInput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::StatsOutput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.density.into_into_dart().into_dart(),
            self.places.into_into_dart().into_dart(),
            self.modes.into_into_dart().into_dart(),
            self.hours.into_into_dart().into_dart(),
            self.weekdays.into_into_dart().into_dart(),
            self.total_distance_m.into_into_dart().into_dart(),
            self.visit_count.into_into_dart().into_dart(),
            self.segment_count.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::StatsOutput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::StatsOutput>
    for crate::api::timeline::StatsOutput
{
    fn into_into_dart(self) -> crate::api::timeline::StatsOutput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::TravelMode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Walking => 0.into_dart(),
            Self::Running => 1.into_dart(),
            Self::Cycling => 2.into_dart(),
            Self::InVehicle => 3.into_dart(),
            Self::InBus => 4.into_dart(),
            Self::InTrain => 5.into_dart(),
            Self::Boat => 6.into_dart(),
            Self::Motorcycling => 7.into_dart(),
            Self::Flight => 8.into_dart(),
            Self::Unknown => 9.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::TravelMode
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::TravelMode>
    for crate::api::timeline::TravelMode
{
    fn into_into_dart(self) -> crate::api::timeline::TravelMode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::UserPlaceInput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.lat.into_into_dart().into_dart(),
            self.lon.into_into_dart().into_dart(),
            self.radius_m.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::UserPlaceInput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::UserPlaceInput>
    for crate::api::timeline::UserPlaceInput
{
    fn into_into_dart(self) -> crate::api::timeline::UserPlaceInput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::VideoParams {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.duration_s.into_into_dart().into_dart(),
            self.period_start_utc.into_into_dart().into_dart(),
            self.period_end_utc.into_into_dart().into_dart(),
            self.style.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::VideoParams
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::VideoParams>
    for crate::api::timeline::VideoParams
{
    fn into_into_dart(self) -> crate::api::timeline::VideoParams {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::VideoPlanErrorKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::UnsupportedDuration => 0.into_dart(),
            Self::EmptyPeriod => 1.into_dart(),
            Self::NothingToRender => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::VideoPlanErrorKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::VideoPlanErrorKind>
    for crate::api::timeline::VideoPlanErrorKind
{
    fn into_into_dart(self) -> crate::api::timeline::VideoPlanErrorKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::VideoPlanResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.error.into_into_dart().into_dart(),
            self.frames.into_into_dart().into_dart(),
            self.fps.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::VideoPlanResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::VideoPlanResult>
    for crate::api::timeline::VideoPlanResult
{
    fn into_into_dart(self) -> crate::api::timeline::VideoPlanResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::VideoStyle {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Classic => 0.into_dart(),
            Self::Night => 1.into_dart(),
            Self::Minimal => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::VideoStyle
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::VideoStyle>
    for crate::api::timeline::VideoStyle
{
    fn into_into_dart(self) -> crate::api::timeline::VideoStyle {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::timeline::VisitInput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.arrival_ts_utc.into_into_dart().into_dart(),
            self.arrival_tz_offset_minutes.into_into_dart().into_dart(),
            self.departure_ts_utc.into_into_dart().into_dart(),
            self.departure_tz_offset_minutes
                .into_into_dart()
                .into_dart(),
            self.lat.into_into_dart().into_dart(),
            self.lon.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::timeline::VisitInput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::timeline::VisitInput>
    for crate::api::timeline::VisitInput
{
    fn into_into_dart(self) -> crate::api::timeline::VisitInput {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::timeline::BucketOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.key, serializer);
        <Option<i64>>::sse_encode(self.place_id, serializer);
        <u32>::sse_encode(self.count, serializer);
        <i64>::sse_encode(self.duration_ms, serializer);
        <f64>::sse_encode(self.distance_m, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::timeline::FiltersInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<i64>>::sse_encode(self.period_start_utc, serializer);
        <Option<i64>>::sse_encode(self.period_end_utc, serializer);
        <Option<i64>>::sse_encode(self.user_place_id, serializer);
        <Option<i64>>::sse_encode(self.geo_place_id, serializer);
        <Vec<crate::api::timeline::TravelMode>>::sse_encode(self.modes, serializer);
    }
}

impl SseEncode for crate::api::timeline::FrameOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.index, serializer);
        <i64>::sse_encode(self.timestamp_utc, serializer);
        <u32>::sse_encode(self.revealed_points, serializer);
        <u32>::sse_encode(self.revealed_segments, serializer);
    }
}

impl SseEncode for crate::api::timeline::HeatCellOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.lat, serializer);
        <f64>::sse_encode(self.lon, serializer);
        <u32>::sse_encode(self.count, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::timeline::BucketOutput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::timeline::BucketOutput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::timeline::FrameOutput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::timeline::FrameOutput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::timeline::HeatCellOutput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::timeline::HeatCellOutput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::timeline::OverrideInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::timeline::OverrideInput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::timeline::PointInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::timeline::PointInput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <f64>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <i64>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::timeline::PrivateZoneInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::timeline::PrivateZoneInput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::timeline::ResolvedPointOutput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::timeline::ResolvedPointOutput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::timeline::ResolvedSegmentOutput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::timeline::ResolvedSegmentOutput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::timeline::ResolvedVisitOutput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::timeline::ResolvedVisitOutput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::timeline::SegmentInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::timeline::SegmentInput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::timeline::TravelMode> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::timeline::TravelMode>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::timeline::UserPlaceInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::timeline::UserPlaceInput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::timeline::VisitInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::timeline::VisitInput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::timeline::VideoPlanErrorKind> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::timeline::VideoPlanErrorKind>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::timeline::OverrideInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <i32>::sse_encode(self.local_date, serializer);
        <f64>::sse_encode(self.start_lat_r, serializer);
        <f64>::sse_encode(self.start_lon_r, serializer);
        <f64>::sse_encode(self.end_lat_r, serializer);
        <f64>::sse_encode(self.end_lon_r, serializer);
        <crate::api::timeline::TravelMode>::sse_encode(self.corrected_mode, serializer);
        <i64>::sse_encode(self.source_start_ts_utc, serializer);
    }
}

impl SseEncode for crate::api::timeline::PipelineRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::timeline::PointInput>>::sse_encode(self.points, serializer);
        <Vec<crate::api::timeline::VisitInput>>::sse_encode(self.visits, serializer);
        <Vec<crate::api::timeline::SegmentInput>>::sse_encode(self.segments, serializer);
        <Vec<crate::api::timeline::UserPlaceInput>>::sse_encode(self.user_places, serializer);
        <Vec<crate::api::timeline::PrivateZoneInput>>::sse_encode(self.private_zones, serializer);
        <Vec<crate::api::timeline::OverrideInput>>::sse_encode(self.overrides, serializer);
        <crate::api::timeline::FiltersInput>::sse_encode(self.filters, serializer);
    }
}

impl SseEncode for crate::api::timeline::PipelineResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::timeline::ResolvedPointOutput>>::sse_encode(self.points, serializer);
        <Vec<crate::api::timeline::ResolvedVisitOutput>>::sse_encode(self.visits, serializer);
        <Vec<crate::api::timeline::ResolvedSegmentOutput>>::sse_encode(self.segments, serializer);
        <Vec<i64>>::sse_encode(self.orphan_override_ids, serializer);
    }
}

impl SseEncode for crate::api::timeline::PlaceOrigin {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::timeline::PlaceOrigin::UserPlace => 0,
                crate::api::timeline::PlaceOrigin::GeoPlace => 1,
                crate::api::timeline::PlaceOrigin::Coordinates => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::timeline::PointInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.timestamp_utc, serializer);
        <i32>::sse_encode(self.tz_offset_minutes, serializer);
        <f64>::sse_encode(self.lat, serializer);
        <f64>::sse_encode(self.lon, serializer);
    }
}

impl SseEncode for crate::api::timeline::PrivateZoneInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.label, serializer);
        <Option<f64>>::sse_encode(self.lat, serializer);
        <Option<f64>>::sse_encode(self.lon, serializer);
        <Option<f64>>::sse_encode(self.radius_m, serializer);
        <Vec<f64>>::sse_encode(self.polygon, serializer);
    }
}

impl SseEncode for crate::api::timeline::ResolvedPointOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.timestamp_utc, serializer);
        <f64>::sse_encode(self.lat, serializer);
        <f64>::sse_encode(self.lon, serializer);
    }
}

impl SseEncode for crate::api::timeline::ResolvedSegmentOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <i64>::sse_encode(self.start_ts_utc, serializer);
        <i32>::sse_encode(self.start_tz_offset_minutes, serializer);
        <i64>::sse_encode(self.end_ts_utc, serializer);
        <i32>::sse_encode(self.end_tz_offset_minutes, serializer);
        <f64>::sse_encode(self.start_lat, serializer);
        <f64>::sse_encode(self.start_lon, serializer);
        <f64>::sse_encode(self.end_lat, serializer);
        <f64>::sse_encode(self.end_lon, serializer);
        <Option<f64>>::sse_encode(self.distance_m, serializer);
        <crate::api::timeline::TravelMode>::sse_encode(self.mode, serializer);
        <bool>::sse_encode(self.corrected, serializer);
        <Option<String>>::sse_encode(self.start_place_label, serializer);
        <Option<String>>::sse_encode(self.end_place_label, serializer);
    }
}

impl SseEncode for crate::api::timeline::ResolvedVisitOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <i64>::sse_encode(self.arrival_ts_utc, serializer);
        <i32>::sse_encode(self.arrival_tz_offset_minutes, serializer);
        <i64>::sse_encode(self.departure_ts_utc, serializer);
        <i32>::sse_encode(self.departure_tz_offset_minutes, serializer);
        <f64>::sse_encode(self.lat, serializer);
        <f64>::sse_encode(self.lon, serializer);
        <Option<String>>::sse_encode(self.place_label, serializer);
        <crate::api::timeline::PlaceOrigin>::sse_encode(self.place_origin, serializer);
        <Option<i64>>::sse_encode(self.place_id, serializer);
    }
}

impl SseEncode for crate::api::timeline::SegmentInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <i64>::sse_encode(self.start_ts_utc, serializer);
        <i32>::sse_encode(self.start_tz_offset_minutes, serializer);
        <i64>::sse_encode(self.end_ts_utc, serializer);
        <i32>::sse_encode(self.end_tz_offset_minutes, serializer);
        <f64>::sse_encode(self.start_lat, serializer);
        <f64>::sse_encode(self.start_lon, serializer);
        <f64>::sse_encode(self.end_lat, serializer);
        <f64>::sse_encode(self.end_lon, serializer);
        <Option<f64>>::sse_encode(self.distance_m, serializer);
        <crate::api::timeline::TravelMode>::sse_encode(self.detected_mode, serializer);
    }
}

impl SseEncode for crate::api::timeline::StatsOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::timeline::HeatCellOutput>>::sse_encode(self.density, serializer);
        <Vec<crate::api::timeline::BucketOutput>>::sse_encode(self.places, serializer);
        <Vec<crate::api::timeline::BucketOutput>>::sse_encode(self.modes, serializer);
        <Vec<crate::api::timeline::BucketOutput>>::sse_encode(self.hours, serializer);
        <Vec<crate::api::timeline::BucketOutput>>::sse_encode(self.weekdays, serializer);
        <f64>::sse_encode(self.total_distance_m, serializer);
        <u32>::sse_encode(self.visit_count, serializer);
        <u32>::sse_encode(self.segment_count, serializer);
    }
}

impl SseEncode for crate::api::timeline::TravelMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::timeline::TravelMode::Walking => 0,
                crate::api::timeline::TravelMode::Running => 1,
                crate::api::timeline::TravelMode::Cycling => 2,
                crate::api::timeline::TravelMode::InVehicle => 3,
                crate::api::timeline::TravelMode::InBus => 4,
                crate::api::timeline::TravelMode::InTrain => 5,
                crate::api::timeline::TravelMode::Boat => 6,
                crate::api::timeline::TravelMode::Motorcycling => 7,
                crate::api::timeline::TravelMode::Flight => 8,
                crate::api::timeline::TravelMode::Unknown => 9,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::timeline::UserPlaceInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.label, serializer);
        <f64>::sse_encode(self.lat, serializer);
        <f64>::sse_encode(self.lon, serializer);
        <f64>::sse_encode(self.radius_m, serializer);
    }
}

impl SseEncode for crate::api::timeline::VideoParams {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.duration_s, serializer);
        <i64>::sse_encode(self.period_start_utc, serializer);
        <i64>::sse_encode(self.period_end_utc, serializer);
        <crate::api::timeline::VideoStyle>::sse_encode(self.style, serializer);
        <String>::sse_encode(self.title, serializer);
    }
}

impl SseEncode for crate::api::timeline::VideoPlanErrorKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::timeline::VideoPlanErrorKind::UnsupportedDuration => 0,
                crate::api::timeline::VideoPlanErrorKind::EmptyPeriod => 1,
                crate::api::timeline::VideoPlanErrorKind::NothingToRender => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::timeline::VideoPlanResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<crate::api::timeline::VideoPlanErrorKind>>::sse_encode(self.error, serializer);
        <Vec<crate::api::timeline::FrameOutput>>::sse_encode(self.frames, serializer);
        <u32>::sse_encode(self.fps, serializer);
    }
}

impl SseEncode for crate::api::timeline::VideoStyle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::timeline::VideoStyle::Classic => 0,
                crate::api::timeline::VideoStyle::Night => 1,
                crate::api::timeline::VideoStyle::Minimal => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::timeline::VisitInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <i64>::sse_encode(self.arrival_ts_utc, serializer);
        <i32>::sse_encode(self.arrival_tz_offset_minutes, serializer);
        <i64>::sse_encode(self.departure_ts_utc, serializer);
        <i32>::sse_encode(self.departure_tz_offset_minutes, serializer);
        <f64>::sse_encode(self.lat, serializer);
        <f64>::sse_encode(self.lon, serializer);
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
